### ISSUE TITLE
[Feature request] Examples for aliases?

### ISSUE THREAD

**Issue by wittekm** [braincore/babel-docs#1]
Hi Ken!

It's been a real pleasure writing stuff with Babel, and I like its focus on clarity and documentation. I was wondering if you'd considering expanding example support to aliases? For example, something along the lines of

```
alias Price = String(pattern="\\d+(\\.\\d{2})?", min_length=1)
  "String containing >1 digit, optionally followed by a period and two digits."

  example default "200 with cents"
    "200.00"
  example three_hundred_no_cents "300 without cents"
    "300" 

struct ArgsWithPrice
  "Defines arguments to /thing/pay"

  price Price
    "Total price paid for a thing"

  example default "An example SomeComplicatedStruct"
    price = three_hundred_no_cents
```

**Comment by braincore** [comment]
Let's keep these feature requests internal :) But, I'm glad you asked, because this is on the todo! We definitely want alias documentation, and we want our documentation to expose aliases directly rather than substituting the aliased type directly. I hadn't thought about having examples specified there as well--I'll give it some thought. Thanks!
